version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    command: bash -c "foreman start -f Procfile.dev"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
